# Generated by Django 5.1.1 on 2024-12-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_availability_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutritional_info',
        ),
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
